# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1370591708);
user_pref("app.update.lastUpdateTime.background-update-timer", 1370591588);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1370591828);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1370620148);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1370613068);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1236);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1370591920740");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1370591922372");
user_pref("datareporting.healthreport.lastPingTime", "1370591922372");
user_pref("datareporting.healthreport.lastSubmitID", "8ff9543a-e23e-47eb-82c3-cc63d5681664");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1370678322372");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1366942651552");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1366942959066");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1366861212354");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 1083);
user_pref("datareporting.sessions.current.main", 23);
user_pref("datareporting.sessions.current.sessionRestored", 1124);
user_pref("datareporting.sessions.current.startTime", "1370504826980");
user_pref("datareporting.sessions.current.totalTime", 5);
user_pref("datareporting.sessions.currentIndex", 18);
user_pref("datareporting.sessions.prunedIndex", 17);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/root/git/clifox/ff/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1368305546000,\"rdfTime\":1368305135000}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.newAddons", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "21.0");
user_pref("idle.lastDailyNotification", 1370623358);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("permissions.default.image", 2);
user_pref("places.database.lastMaintenance", 1370591921);
user_pref("places.history.expiration.transient_current_max_pages", 52519);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1370536958);
user_pref("toolkit.startup.last_success", 1370504827);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1373096947);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
